version: "3.8"
services:
  frontend:
    build:
      context: ./packages/client
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    networks:
      - app-network

  backend:
    build:
      context: ./packages/server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - app-network

networks:
  app-network:
